theme: jekyll-theme-minimal
title: Compumbia University E1006I
description: This is the github project for _Introduction to Computing For Engineers and Applied Scientists_, focusing
on the Spring 2018 semester. The site primarily contains course presentations, related Jupyter notebooks and
sample code.