theme: jekyll-theme-minimal
title: Columbia University E1006I
description: This is the github project for Introduction to Computing For Engineers and Applied Scientists, focusing on the Spring 2018 semester. The site primarily contains course presentations, related Jupyter notebooks and sample code.